server:
  port: 9191
  servlet:
    context-path: /recdoc
    http2:
      enabled: true
    compression:
      enabled: true
      mime-types: application/json,application/xml,text/html
      min-response-size: 1024
spring:
  application:
    name: doc-rag-ai
  ai:
    vectorstore:
      weaviate:
        host: localhost:8080
        scheme: http
        filter-field:
          uid: TEXT
    ollama:
      embedding:
        model: nomic-embed-text
      base-url: http://localhost:11434
      chat:
        model: llama3:8b
logging:
  level:
    org.khodyko.docragai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"