server:
  port: 9191
  servlet:
    context-path: /recdoc
    http2:
      enabled: true
    compression:
      enabled: true
      mime-types: application/json,application/xml,text/html
      min-response-size: 1024
spring:
  application:
    name: doc-rag-ai
  ai:
#    embedding:
#      ollama:
#        base-url: http://localhost:11434
#        model: mxbai-embed-large
#    vectorstore:
#      weaviate:
#        host: localhost:8080
#        scheme: http
#        filter-field:
#          uid: TEXT
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3:8b
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-4o
logging:
  level:
    org.khodyko.docragai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"